env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
# rules:
#   vue/multi-word-component-names: off
#   vue/no-v-model-argument: off
#   @typescript-eslint/no-empty-function: off
#   @typescript-eslint/no-explicit-any: off
