# Reference: https://prettier.io/docs/en/options.html
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: 'as-needed'
jsxSingleQuote: false
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: false
arrowParens: 'always'
requirePragma: false
insertPragma: false
proseWrap: 'never'
htmlWhitespaceSensitivity: 'css'
vueIndentScriptAndStyle: false
endOfLine: 'lf'
